"""Property test P19 (webhook subscription portion): audit emission for terminal transitions.

Per design §Property 19 (Requirements 7.2, 9.4), every terminal transition
on a webhook subscription — create, update, rotate-secret, delete — must
append exactly one row to ``audit_logs`` whose ``action`` matches the
canonical verb, whose ``user_id`` is the actor, and whose
``resource_type`` / ``resource_id`` reference the subscription.

This module exercises the subscription portion of Property 19. The
companion sub-tasks 4.7, 8.7, 11.11, and 13.5 cover the api-key,
webhook-delivery, export, and rate-limit portions respectively. Per
design §Component 3, the four canonical verbs are
``webhook.subscription.create``, ``webhook.subscription.update``,
``webhook.subscription.rotate_secret``, and
``webhook.subscription.delete``.

Strategy
--------

For every Hypothesis example we:

1. Insert a fresh JWT-authenticated owner via a per-example
   committing session so the route can read it back via the API
   stack. A unique email per example keeps owners from colliding
   across the function-scoped fixture lifetime.
2. Hit ``POST /api/v1/webhooks/`` to create a subscription and
   capture its id. The ``create`` action is part of the per-example
   sequence by construction — it has to be the first transition
   because every subsequent verb references the same subscription
   id.
3. Apply a Hypothesis-generated sequence drawn from
   ``{update, rotate_secret, delete}``. Soft-delete is terminal in
   the lifecycle (the route's idempotency check skips the audit
   write on a second delete, per
   ``app.api.v1.webhooks.delete_webhook_subscription``); we model
   that by truncating the action sequence at the first ``delete``.
   Updates carry a ``description`` change so the route's
   ``changed`` dict is non-empty and the audit row is emitted (the
   route also skips the audit write on a no-op patch).
4. Query ``audit_logs`` filtered by the subscription id and the
   four canonical verbs and assert (a) exactly one row per executed
   transition, (b) verb labels match the executed action types,
   (c) ``user_id`` equals the owner, (d) ``resource_type`` is
   ``webhook_subscription``, and (e) ``resource_id`` equals the
   subscription id.

Session-management note
-----------------------

The shared ``conftest.db_session`` fixture wraps the test in
``async with session.begin() as transaction:`` and rolls back at
teardown. That pattern is incompatible with property tests that
hit committing routes across many Hypothesis examples: the first
route ``db.commit()`` closes the wrapper's inner transaction, and
the second example then trips
``InvalidRequestError: Can't operate on closed transaction inside
context manager`` on the next session operation. To avoid that
brittleness we build a per-test session factory bound to the
function-scoped ``test_engine`` and override
:func:`app.database.get_db` ourselves, giving each route call a
fresh, autocommit-style session and using a separate fresh session
for in-test verification queries.

# Feature: api-platform-export, Property 19: Audit emission for terminal transitions
# Validates: Requirements 7.2, 9.4
"""

from __future__ import annotations

import uuid
from typing import AsyncIterator, List, Tuple

import pytest
import pytest_asyncio
from hypothesis import HealthCheck, given, settings, strategies as st
from httpx import ASGITransport, AsyncClient
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from app.core.audit import API_PLATFORM_VERBS
from app.core.security import create_access_token, hash_password
from app.database import get_db
from app.main import app
from app.models.audit_log import AuditLog
from app.models.user import User


# ── Constants ─────────────────────────────────────────────────────────

#: Canonical verbs emitted by the four terminal transitions on a
#: webhook subscription. Pinning the literal strings here keeps the
#: test honest if the registry ever drops or renames a verb — the
#: assertion would fail rather than silently filter the row out.
_SUBSCRIPTION_VERBS: Tuple[str, ...] = (
    "webhook.subscription.create",
    "webhook.subscription.update",
    "webhook.subscription.rotate_secret",
    "webhook.subscription.delete",
)

#: Mapping from action labels generated by the Hypothesis strategy to
#: the canonical verb the route emits for that action.
_ACTION_TO_VERB = {
    "create": "webhook.subscription.create",
    "update": "webhook.subscription.update",
    "rotate_secret": "webhook.subscription.rotate_secret",
    "delete": "webhook.subscription.delete",
}


# ── Strategies ────────────────────────────────────────────────────────

# Each non-create action: update / rotate_secret / delete. ``create``
# is implicit on every example as the first transition — no point
# generating the empty sequence and special-casing it.
_FOLLOW_UP_ACTION = st.sampled_from(["update", "rotate_secret", "delete"])

# 0..6 follow-up actions per example. Hypothesis truncates at the
# first ``delete`` (see :func:`_truncate_at_delete`) because the
# route's idempotency clause skips the audit write on a second
# delete and the test should not assert on rows that never get
# written.
_FOLLOW_UP_SEQUENCE = st.lists(
    _FOLLOW_UP_ACTION,
    min_size=0,
    max_size=6,
)


def _truncate_at_delete(actions: List[str]) -> List[str]:
    """Drop everything after the first ``delete`` in the action list.

    The webhook delete route is idempotent: ``await db.flush()`` and
    the audit emission only run when the row's ``active`` flag flips
    from True to False. A second delete on an already-inactive row is
    a no-op that emits no audit row, so the property "exactly one
    audit row per executed transition" only holds for the prefix up
    to and including the first delete. Updates and rotates after a
    delete still emit audit rows, but we exclude them from the
    Hypothesis input space rather than complicate the assertion.

    Args:
        actions: Generated action list from the Hypothesis strategy.

    Returns:
        The longest prefix of ``actions`` that contains at most one
        ``delete``, with the ``delete`` (if present) at the tail.
    """
    out: List[str] = []
    for a in actions:
        out.append(a)
        if a == "delete":
            break
    return out


# ── Fixtures ──────────────────────────────────────────────────────────


@pytest_asyncio.fixture
async def p19_session_factory(test_engine) -> async_sessionmaker:
    """Build a session factory bound to the function-scoped test engine.

    Each call to the factory yields a fresh :class:`AsyncSession` with
    no outer ``session.begin()`` wrapper, so the route layer's
    ``await db.commit()`` calls succeed without invalidating later
    operations across Hypothesis examples (see module docstring).

    ``expire_on_commit=False`` mirrors the production session factory
    so attribute access on the user / subscription rows after commit
    behaves the same way the route does.
    """
    return async_sessionmaker(
        test_engine, class_=AsyncSession, expire_on_commit=False
    )


@pytest_asyncio.fixture
async def p19_client(
    p19_session_factory: async_sessionmaker,
) -> AsyncIterator[AsyncClient]:
    """HTTP client that injects a fresh route session per request.

    Replaces the conftest-wide ``async_client`` fixture for this
    property test only. The dependency override returns a brand-new
    session for each ``Depends(get_db)`` resolution, so the route's
    ``await db.commit()`` is the natural commit-and-close pattern
    rather than fighting the conftest's transaction wrapper.
    """

    async def _fresh_route_db() -> AsyncIterator[AsyncSession]:
        async with p19_session_factory() as s:
            yield s

    app.dependency_overrides[get_db] = _fresh_route_db
    transport = ASGITransport(app=app)
    try:
        async with AsyncClient(
            transport=transport, base_url="http://test"
        ) as client:
            yield client
    finally:
        app.dependency_overrides.clear()


# ── Helpers ───────────────────────────────────────────────────────────


async def _make_owner(p19_session_factory) -> Tuple[str, str]:
    """Insert a fresh owner user and return (user_id, JWT bearer token).

    Uses its own session that commits cleanly so the route's API stack
    can authenticate the JWT without depending on uncommitted state
    from another session. A unique email per call keeps owners from
    colliding across Hypothesis examples that share the
    function-scoped session factory.
    """
    async with p19_session_factory() as s:
        user = User(
            email=f"p19-webhook-{uuid.uuid4().hex[:12]}@example.com",
            hashed_password=hash_password("Test1234!"),
            display_name="P19 Owner",
        )
        s.add(user)
        await s.commit()
        await s.refresh(user)
        user_id = user.id
    return user_id, create_access_token(user_id)


async def _create_subscription(client: AsyncClient, headers: dict) -> str:
    """Create a webhook subscription and return its id.

    Uses a minimal valid payload (HTTPS target URL, one supported
    event type) so the route accepts it without exercising any
    validation edge cases that are out of scope for Property 19.
    """
    resp = await client.post(
        "/api/v1/webhooks/",
        headers=headers,
        json={
            "target_url": "https://hooks.example.com/p19",
            "event_types": ["response.created"],
            "description": "P19 audit emission test",
        },
    )
    assert resp.status_code == 201, resp.text
    return resp.json()["id"]


async def _apply_action(
    client: AsyncClient,
    headers: dict,
    sub_id: str,
    action: str,
    counter: int,
) -> None:
    """Hit the route corresponding to ``action`` against ``sub_id``.

    ``counter`` is folded into the update payload so each update
    generates a distinct ``description`` value and the route's
    ``changed`` dict is non-empty. The route only emits an audit row
    when at least one field actually changes; passing identical
    descriptions across calls would turn a generated ``update`` into
    a no-op and break the row-count assertion.
    """
    if action == "update":
        resp = await client.patch(
            f"/api/v1/webhooks/{sub_id}",
            headers=headers,
            json={"description": f"P19 patch #{counter}"},
        )
        assert resp.status_code == 200, resp.text
    elif action == "rotate_secret":
        resp = await client.post(
            f"/api/v1/webhooks/{sub_id}/rotate-secret",
            headers=headers,
        )
        assert resp.status_code == 200, resp.text
    elif action == "delete":
        resp = await client.delete(
            f"/api/v1/webhooks/{sub_id}",
            headers=headers,
        )
        assert resp.status_code == 204, resp.text
    else:  # pragma: no cover — guarded by the strategy
        raise AssertionError(f"unknown action {action!r}")


async def _query_audit_rows(
    p19_session_factory, sub_id: str
) -> List[AuditLog]:
    """Return every audit row whose ``resource_id`` is ``sub_id``.

    Filtering server-side by the subscription id keeps the row set
    small even when the shared engine accumulates entries from prior
    Hypothesis examples — each example owns its own subscription id
    and so its own audit row set.
    """
    async with p19_session_factory() as s:
        result = await s.execute(
            select(AuditLog)
            .where(AuditLog.resource_id == sub_id)
            .where(AuditLog.action.in_(_SUBSCRIPTION_VERBS))
            .order_by(AuditLog.id.asc())
        )
        return list(result.scalars().all())


# ── Pre-flight invariants on the registry ─────────────────────────────


# Feature: api-platform-export, Property 19: Audit emission for terminal transitions
# Validates: Requirements 7.2, 9.4
def test_p19_subscription_verbs_are_registered() -> None:
    """Every verb the test asserts on belongs to ``API_PLATFORM_VERBS``.

    A regression that drops one of the four verbs from the canonical
    registry would silently skip the audit emission on the matching
    transition. Pinning the literals here surfaces the drift before
    the rest of the property test runs.
    """
    for verb in _SUBSCRIPTION_VERBS:
        assert verb in API_PLATFORM_VERBS, (
            f"verb {verb!r} expected in API_PLATFORM_VERBS but missing"
        )


# ── The property test ────────────────────────────────────────────────


# Feature: api-platform-export, Property 19: Audit emission for terminal transitions
# Validates: Requirements 7.2, 9.4
@pytest.mark.asyncio
@given(follow_up_actions=_FOLLOW_UP_SEQUENCE)
@settings(
    max_examples=50,
    deadline=None,
    suppress_health_check=[HealthCheck.function_scoped_fixture],
)
async def test_p19_webhook_subscription_audit_emission(
    p19_client: AsyncClient,
    p19_session_factory: async_sessionmaker,
    follow_up_actions: List[str],
) -> None:
    """Each terminal transition writes exactly one matching audit row.

    Sub-invariants asserted in lock-step:

    * Row count equals the number of executed transitions
      (``1`` for the implicit ``create`` plus the truncated
      follow-up sequence). A row count higher than the executed
      count would mean a route fired more than one audit row per
      transition; lower would mean a transition silently elided
      the audit emission.
    * The ordered ``action`` column equals the canonical verb
      list for the executed transitions. Order matches the
      ``audit_logs.id`` autoincrement sequence, which the route
      preserves because each transition's flush completes before
      the next request begins.
    * Every row's ``user_id`` equals the JWT-authenticated owner.
    * Every row's ``resource_type`` is ``"webhook_subscription"``
      and every row's ``resource_id`` is the subscription id.

    Validates: Requirements 7.2, 9.4.
    """
    user_id, token = await _make_owner(p19_session_factory)
    headers = {"Authorization": f"Bearer {token}"}

    # The first transition is always ``create``; route assertions on
    # row count are in terms of (1 + executed follow-ups).
    sub_id = await _create_subscription(p19_client, headers)

    executed = _truncate_at_delete(follow_up_actions)

    # Update payloads need a per-call counter so the route's
    # ``changed`` dict stays non-empty across consecutive updates.
    update_counter = 0
    for action in executed:
        if action == "update":
            update_counter += 1
        await _apply_action(
            p19_client, headers, sub_id, action, update_counter
        )

    expected_verbs: List[str] = [_ACTION_TO_VERB["create"]] + [
        _ACTION_TO_VERB[a] for a in executed
    ]

    rows = await _query_audit_rows(p19_session_factory, sub_id)

    actual_verbs = [r.action for r in rows]
    assert actual_verbs == expected_verbs, (
        f"audit verb sequence mismatch for subscription {sub_id}: "
        f"expected {expected_verbs}, got {actual_verbs}; "
        f"executed actions: {['create'] + executed}"
    )

    for row in rows:
        assert row.user_id == user_id, (
            f"audit row {row.id} (action={row.action!r}) has "
            f"user_id={row.user_id!r}, expected owner {user_id!r}"
        )
        assert row.resource_type == "webhook_subscription", (
            f"audit row {row.id} (action={row.action!r}) has "
            f"resource_type={row.resource_type!r}, expected "
            f"'webhook_subscription'"
        )
        assert row.resource_id == sub_id, (
            f"audit row {row.id} (action={row.action!r}) has "
            f"resource_id={row.resource_id!r}, expected {sub_id!r}"
        )
